import { useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import FadeIn from 'react-fade-in';
import Image from 'next/image'

export default function Home() {
  const [raffle, setRaffle] = useState();
  const [win, setWin] = useState(false);

  const raffleNames = async event => {
    event.preventDefault()

    const names = event.target.list.value.split(',')
    const totalNames  = names.length;

    const raffleList = []
    
    let count = 0;
    
    function getRandomInt(min, max) {
      min = Math.ceil(min);
      max = Math.floor(max);
      return Math.floor(Math.random() * (max - min)) + min;
    }
    
    do {
      const random = getRandomInt(0, names.length);

      raffleList.push({
        name: names[random],
        quantity: names.length,
        percentage: (100/names.length).toFixed(2)
      })

      names.splice(random, 1)
      count++
    } while (count < totalNames);

    setRaffle(raffleList)

    console.log(raffle)
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Sorteio do Azarão</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rob.svg" />
      </Head>

      <main className={styles.main}>
        <Image src="/rob.svg" alt="r0bmai" width={150} height={120} />

        <h1 className={styles.title}>
          Sorteio do Azarão 
        </h1>

        <p className={styles.description}>
          
          <code className={styles.code}><a href="https://www.twitch.tv/r0bmais">r0bmais</a></code>
        </p>

        
        <FadeIn className={styles.grid} childTag="a" childClassName={win ? styles.cardwin : styles.removed} delay={2000}>
            {raffle ? raffle.map((person, index) => {
               
              return (
                  <span className={person.quantity === 1 ? styles.cardwin : styles.cardloser} key={index}>
                    <p>{person.quantity === 1 ? 'Ganhador' : 'Removido'}</p>
                    <h2>{`${person.name}`}</h2>
                    <p><strong>{person.percentage}%</strong></p>
                  </span>
              )
            }) : ''}
        </FadeIn>
        
        <form onSubmit={raffleNames} className={styles.form}>
          <input type="text" name='list' id='list'/>
          <button type="submit">Sortear</button>
        </form>
      </main>

      <footer className={styles.footer}>
        Developed by Lead
      </footer>
    </div>
  )
}
